### ISSUE TITLE
`Read()` to error

### ISSUE THREAD

**Issue by d1y** [skanehira/clipboard-image#4]
```bash
❯❯❯ go run
error
panic: exit status 1: 7:36: execution error: Can’t make some data into the expected type. (-1700)
```

os: macos 11.0.1 (20B50)
![Screen Shot 2020-12-19 at 17 08 46](https://user-images.githubusercontent.com/45585937/102685600-e4cba180-421c-11eb-9460-501fa9278e15.png)

**Comment by skanehira** [comment]
Can you let me know minimal source code?
